### ISSUE TITLE
Chrome Version Not Working

### ISSUE THREAD

**Issue by seveerekaj** [pvrs12/Anesidora#5]
There is a problem with the last update to the Chrome version of this extension. It will play one song, then stop. Clicking the Anesidora icon and then clicking "play" will replay the current song. The only way to get it to go to the next song is to click the "next" button, and this must be done every time the current song ends.
FYI I am running Windows 10, Chrome version 62.0.3202.75, Anesidora version 1.10.0.
The current Firefox version does not have this problem. Before the last update, the Chrome extension did not have this problem.

**Comment by pvrs12** [comment]
Thanks for the report. I have a pretty good idea what the cause likely is (related to how I handled the Android stuff). I'll look into it tonight or tomorrow

**Comment by pvrs12** [comment]
I've separated out the Chrome version from the Firefox version and have reverted the changes that I made which broke Chrome. 

This version should fix the issue, but if you keep experiencing it, let me know. It's published on the chrome store and is also available from the Releases tab https://github.com/pvrs12/Anesidora/releases/tag/v1.10.2

**Comment by seveerekaj** [comment]
I got the latest version from the Chrome store (it says version 1.10.3), but now the icon won't even open up a menu or anything. Clicking the icon does nothing. I tried rebooting my PC and rebooting Chrome and it didn't fix the problem.

**Comment by pvrs12** [comment]
I'm apparently just awful at testing the Chrome version of this extension... I had a typo in the package script which caused it to use resources from Firefox instead of those from Chrome. That should be fixed now for 1.10.4 which is uploading to the Chrome webstore right now

Thank you again for testing this out!

**Comment by seveerekaj** [comment]
Works great! Thanks for fixing it, I absolutely love this extension!

**Comment by seveerekaj** [comment]
This issue seems to have popped up again, after the latest update to the extension. Same as before - Chrome, playback stops after 1 song.

**Comment by pvrs12** [comment]
Oof. I'll roll back the release for chrome. Sorry about that. I'll do a bit more testing and try to figure out what's up. I don't think it is as simple as the last time

**Comment by pvrs12** [comment]
I've rolled it back to what was version 1.10.4 (now 1.11.1 so it will update for you).

I'll look into what is causing this. I did do some major changes of the code so that it was easier to read. I probably inadvertently changed something else as well.

**Comment by seveerekaj** [comment]
Did you publish it to the Chrome Web Store? It claims that the current version is 1.11.0, and the problem still exists in this version...

**Comment by pvrs12** [comment]
Looks like I just left it as a draft. Try again in a few minutes

**Comment by EnorMOZ** [comment]
Version: 1.11.1
Chrome Version: 68.0.3409.2
OS: OSX 10.11.6. 

Issue: It keeps prompting for user/pass.

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Stack Trace
js/jquery/jquery-3.2.1.min.js:4 (send)`

`The SSL certificate used to load resources from https://tuner.pandora.com has been distrusted. See https://g.co/chrome/symantecpkicerts for more information.
Context
background.htm
Stack Trace
background.htm:0 (anonymous function)`

**Comment by wolff000** [comment]
I am also unable to connect.  it continually denies a working username and password.  I can log in on the Pandora site with no issue.  It is apparently only an issue with the chrome version as firefox still works.

**Comment by seveerekaj** [comment]
@EnorMOZ @jmgwilson looks like your issue may actually be issue #19

**Comment by wolff000** [comment]
@seveerekaj that did fix my issue.  thanks
