### ISSUE TITLE
Firefox android - not playing next song automatically

### ISSUE THREAD

**Issue by swan77777** [pvrs12/Anesidora#84]
Hello again,
So when a song finishes, it does not automatically move and play the next song (Firefox Nightly on Android). I can advance it manually by pressing the next song button on the screen, however. Is there a setting I should be changing to allow the auto-advance?
Thanks.

**Comment by pvrs12** [comment]
I'll check into this. There isn't any setting for it and it _should_ happen automatically.

**Comment by swan77777** [comment]
I saw you pushed a fix - the screen for Anesidora is now a blank window when I open it. My phone just updated so it may have been something on my end. Does it still work fine for you? Thanks again.

**Comment by pvrs12** [comment]
Heh, well it did work, but #85 happened due to mistakes I made... Once those square out I'll update this again

**Comment by swan77777** [comment]
Hello, just seeing if there's been any updates with this issue, in case it got forgotten or buried somehow. Thanks.

**Comment by pvrs12** [comment]
Tbh, I haven't worked on this addon in ages. Been really busy with real
work...

This one is also pretty low priority since there's only 2 android users
right now and I think one of them is me.

This is open if you or anyone wants to try to tackle it. I'll accept the PRs

**Comment by lovelydumpling** [comment]
To be fair, I'm still having the issue on Chrome (Brave) where it stops automatically playing after a few tracks, and I have to skip to the next song manually myself. I wonder if the two issues are related.

**Comment by hucario** [comment]
I can confirm this happens to me occasionally. It's probably a network thing (request fails and doesn't retry?) so I'll keep devtools for Anesidora open in the background logging network requests and with conditional breakpoints to try to find it.

**Comment by hucario** [comment]
alright, I don't know if this is the _cause_ but this is a separate bug I found:
You see this? This line of code right here?
![image](https://user-images.githubusercontent.com/50851047/137609862-176bebda-8438-49aa-81de-72d4b2665d00.png)
It indicates whether the previous request failed. Guess what? It's in the wrong place. It's defined in the function, which means it always is false. So Anesidora fails station.getPlaylist(), and because of this line here:
![image](https://user-images.githubusercontent.com/50851047/137609886-b0a78b6f-7ce4-40c0-8b60-c5093eeb0694.png)
It retries again, and again, and again. Causing _many_ requests to go to Pandora, which _is not good_ and causes them to rate limit you, which means it never solves. 

I'll put through a PR to fix this Soon:tm:

**Comment by pvrs12** [comment]
https://github.com/pvrs12/Anesidora/actions/runs/1487849746
@swan77777 is it possible for you to test the builds in this?

https://github.com/pvrs12/Anesidora/pull/96

i believe this should fix the android issues

**Comment by nswanson777777** [comment]
Hey this is swan77777 (lost access to old github account). Sorry for the late reply. I just reinstalled Anesidora for Firefox Nightly on Android, and it still is not automatically going to the next song. Let me know if you want me to test anything on my end. Thanks.

**Comment by nswanson777777** [comment]
Actually I'm not sure that I'm getting the changes on the adroid_fixes branch. The date of the code pulled is the same but it looks like the master branch was also updated on that same date. I don't have an easy way to check this further on my phone, and I don't see a way to pull a specific branch of the code inside Firefox Nightly Android.

**Comment by hucario** [comment]
Reconfirming - just got Firefox Nightly for Android, and the bug still exists. Anesidora works on desktop, which means that the issue is almost certainly a webcompat issue which is pain. 
I'm _hoping_ that the issue is in platform_specific.js, because then I can just move calling that to after the listeners and everything will work again. If it's not that, it means I have to go looking around the code for whatever it is that FFNA doesn't support.
It's also possible that it's an issue with Android's battery saver stopping the process in the background, but it doesn't look like that's the case based on the symptoms (would probably halt in the middle of a song, rather than stopping the playing of new ones)

**Comment by Bolongna** [comment]
I can duplicate this issue on chrome but it is easy to fix on chrome. To make it happen, sign in to pandora in another window, then don't sign out, then use Anesidora as normal. It will play one to two songs and stop. Then click next and it does the same. If you then go and sign out it will still act the same way until you delete the cookies and then it starts working again. Not sure if that helps or not.

**Comment by hucario** [comment]
Hey, sorry I stopped responding here.
I'm going to try to reproduce this over the next week to see if this is still an issue.

**Comment by Bolongna** [comment]
No problem, life catches all of us at times. FYI I've been running andy on chrome and edge without many issues, The latest update killed it on chrome until I figured out a way to force it to allow the older extensions. Would love it if there was a way to get it to work under V3 manifest, if possible. 
I don't think it still is doing the above, at least it doesn't here any longer.

**Comment by hucario** [comment]
Glad it's no longer an issue!
As to manifest v3, I just posted a summary here: #104 
In short, manifest is only relevant for Chrome users who are using developer mode anyways, because we've been removed from the Chrome web store by Pandora. If you're *going* to use developer mode, you can load mv2 pretty easily. If we were to rejoin the Chrome Web Store somehow, this would be a major issue and I'd probably implement the "tabful" mode I mention in #104, but as it isn't - I'm not.
